name: Compile LaTeX document
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/Definitionen.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Compiled-PDF
          path: src/Definitionen.pdf